use_frameworks!

target 'SupremeRestKit_Example' do
  pod 'SupremeRestKit', :path => '../'

  target 'SupremeRestKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  
  end
end
